# NOTE: This workflow is not used by the nominer variant.
name: ci/gh-actions/verify
on:
  workflow_dispatch:
jobs:
  p2pool-hashes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Verify Hashes (disabled by default)
      run: |
        echo "P2Pool binary verification is currently disabled."
        # python3 .github/verify_p2pool.py
